### ISSUE TITLE
添加对spring native的支持

### ISSUE THREAD

**Issue by tiro8183** [baomidou/dynamic-datasource#465]
![image](https://user-images.githubusercontent.com/28704881/204421233-b0b08471-bf02-4034-a890-b8a108a78f44.png)

# Enviroment

JDK Version(required): graalvm-ce-java11-22.3.0

SpringBoot Version(required): 2.7.5

dynamic-datasource-spring-boot-starter Version(required):3.5.2

druid Version(optional):

# Describe what happened
Native Build Tools构建本地可执行文件时出现

Expected Result:

Actual Result:

If there is an exception,or aop invalid,please attach the exception trace:

```
Just paste your stack trace here!
```

# Steps to reproduce

- Step 1 

- Step 2 

- Step 3

**Comment by tiro8183** [comment]
可能与此有关
![image](https://user-images.githubusercontent.com/28704881/204422083-938b0972-2255-4f86-b3ce-8e02d115ee20.png)

**Comment by linghengqian** [comment]
- You can make unit tests, and then you can submit a PR for GraalVM reachability metadata to https://github.com/oracle/graalvm-reachability-metadata.
- Since Spring Native is already in maintenance, we should only focus on native GraalVM support.
- @huayanYu Can you release a new version so that you we can write unit tests under Spring Boot 3.0.0?

**Comment by huayanYu** [comment]
focus on this issue  , 3.6.0 relased ,springboot3 support ,

**Comment by cutehuman** [comment]
> focus on this issue , 3.6.0 relased ,springboot3 support ,

very nice

**Comment by linghengqian** [comment]
- I work on this issue.

**Comment by linghengqian** [comment]
- Blocked by https://github.com/oracle/graalvm-reachability-metadata/pull/154#discussion_r1054645574. Spring Framework has taken over the user's configuration of GraalVM Native Build Tools.

**Comment by linghengqian** [comment]
- Blocked by https://github.com/baomidou/dynamic-datasource-spring-boot-starter/issues/471 . SPEL-related functionality fails unit tests.

**Comment by linghengqian** [comment]
@akun471 

- Hi, I did create https://github.com/linghengqian/dynamic-datasource-nativetest for testing.  

- But this issue was first blocked by https://github.com/spring-projects/spring-framework/issues/30281.  This issue is currently unsolvable without the Spring Team interpreting the settings related to `NativeDetector#inNativeImage` and resolving conflicts with GraalVM Native Build Tools.

**Comment by linghengqian** [comment]
@tiro8183 
- Please change the issue title to English for easy search.

**Comment by huayanYu** [comment]
@linghengqian 4.0.0 release can u go on this issue?

**Comment by linghengqian** [comment]
> @linghengqian 4.0.0 release can u go on this issue? 

- An interesting fact is that the Spring Team did not continue to respond to https://github.com/spring-projects/spring-framework/issues/30281#issuecomment-1580272140 .  

- I've been quite busy these two weeks, so let me take a look at the 6.1.0-SNAPSHOT version of the Spring Framework this weekend.
